geeksforsocialchange/gfsc-v3

config.yaml
Fixes #245 
- updated build command to `hugo -b $CF_PAGES_URL` in cloudflare dashboard
- add `https://gfsc.studio` to  `CF_PAGES_URL` in cloudflare dashboard
- make the baseURL relative in hugo config
=> update baseURL to / so branch previews work

README.md, netlify.toml, themes/gfsc/layouts/our-work/list.html, themes/gfsc/layouts/partials/projectindex.html, themes/gfsc/layouts/partials/title.html, themes/gfsc/layouts/project/single.html
Fixes #156
- I choose version `0.111.3`  because we already got people set up with that when we did the towers
- mostly big find and replace job
- I've updated cloudflare environment variable and the readme
https://dash.cloudflare.com/a51f3d420a4df91985d494964c2b573d/pages/view/gfsc/ef8c40b9-ee7b-447a-8280-d41f9470b926
=> migrate to hugo version 0.111.3

content/blog/2021/everything-is-connected/index.md
Fixes #233
- we had an old jekyll / liquid shortcode that needed moving to a hugo one
scroll down to the Gattaca film still https://233-raw-template-on-producti.gfsc.pages.dev/blog/2021/everything-is-connected/
=> refactor old jekyll shortcode to add image to blog

themes/gfsc/assets/sass/base/_typography.sass, themes/gfsc/assets/sass/pages/_blog.sass
Fixes #230 
- increase fontsize to 1.2 of body text so we meet WCAG AA
- fixed in the typography file and removed the conflicting styles in the blog file, this accidentally fixes  #194 
Now quotes are larger some judgement will be needed by people adding content to not included really long quotes like on TSN 
https://0b10bb4d.gfsc.pages.dev/blog/2023/raftt-design-blog-2/
=> fix accessibility issues on blockquotes with tiny text

content/blog/2016/no-false-users/index.md, content/blog/2018/placecal-story-so-far/index.md, documentation/shortcodes.md, themes/gfsc/assets/sass/base/_utility.sass, themes/gfsc/assets/sass/pages/_blog.sass, themes/gfsc/layouts/shortcodes/youtube.html
Fixes #176 
- youtube embed didn't work because it was being passed 2 named args but it took a single non-named arg
- converted to named params to avoid ordering bugs
- updated docs
- moved video specific css out of the blog file
=> improvements to usability of youtube shortcode

content/privacy-policy/index.md, themes/gfsc/layouts/privacy/single.html
Fixes #249 
- added a markdown file with dummy content
- added a layout file
https://249-privacy-page.gfsc.pages.dev/privacy-policy/
=> add a privacy policy page

themes/gfsc/assets/sass/components/_footnotes.sass, themes/gfsc/assets/sass/pages/_blog.sass
Fixes #229 
- move some footnote styling out of a blog sass file
- footnotes are the same size as body text
- remove hr to reduce distance of footnotes to article body
- up to author if they want to place a donate element etc at the end of the article
in action https://db3da797.gfsc.pages.dev/blog/2022/why-is-it-so-hard-to-do-nice-things/
=> footnotes have style

themes/gfsc/layouts/shortcodes/image-with-caption/start.html, themes/gfsc/layouts/shortcodes/image.html
Fixes #276 
- check width of image before resizing.
=> only resize images that are larger than 900px wide in shortcodes

themes/gfsc/assets/sass/components/_theme-tags.sass, themes/gfsc/assets/sass/main.scss, themes/gfsc/assets/sass/pages/_work.sass, themes/gfsc/layouts/partials/projectindex.html, themes/gfsc/layouts/partials/themeTags.html
Fixes #267 
- add themes to project preview cards
- link through to filtered theme list
- create a `themesTag` partial so we can add it to the project single page when we are ready
- use link styling because they are links!
=> 267 tags on project list

.prettierignore, themes/gfsc/layouts/shortcodes/gallery-with-caption/start.html, themes/gfsc/layouts/shortcodes/image-with-caption/start.html
Fixes #294 
- Fixes broken shortcode - prettier had helpfully added closing tags onto the first part of the shortcode which meant the elements were closed before we could add the text
- Checks all two part shortcodes are added to `.prettierignore`
=> Fix broken shortcode & clip the wings on overzealous prettier

themes/gfsc/assets/sass/base/_footer.sass
Fixes #306 
- Make it the same color as other text.
- This feels like the easiest fix. Making it large and bright orange would draw to much attention too details that are not the main content.
=> improve footer contrast

themes/gfsc/assets/sass/pages/_project.sass
Fixes #321
- add the same list stylings from typography into the projects sass file.
- it's scoped under `.project__content` because otherwise the themes list inherits some very large margins
=> improve color contrast of unordered lists in projects

themes/gfsc/assets/sass/base/_header.sass, themes/gfsc/layouts/partials/header.html
Fixes #322 
- on devices that have the burger menu present
- allow focus to show up as an outline
- can tab into and out of the menu (when not showing the nav links)
- can toggle the nav links
- when nav links visible- can tab through nav links after burger menu
=> Burger menu keyboard tab navigation

themes/gfsc/assets/sass/components/_buttons.sass, themes/gfsc/layouts/our-work/list.html
Fixes #323 
- converted `a` elements to `button`s 
- updated some styles as buttons come with some default formatting that wasn't accounted for in the css
I uncovered a new issue while working on this #331
=> improve keyboard usability of poject filters

themes/gfsc/assets/sass/base/_utility.sass, themes/gfsc/layouts/_default/baseof.html
Fixes #324 
- first tab item links past the header/nav and into the main element
=> add skip to content link

content/blog/2018/placecal-story-so-far/index.md, content/blog/2021/everything-is-connected/index.md, content/blog/2021/technology-isnt-a-magic-wand/index.md, content/blog/2021/what-happened-to-nuclear-free-manchester/index.md
Fixes #315
- Updates some gallery alt text so that it better describes the images & is applied to images individually
https://3718cd02.gfsc.pages.dev/blog/2018/placecal-story-so-far/
https://3718cd02.gfsc.pages.dev/blog/2021/everything-is-connected/
https://3718cd02.gfsc.pages.dev/blog/2021/technology-isnt-a-magic-wand/
https://3718cd02.gfsc.pages.dev/blog/2021/what-happened-to-nuclear-free-manchester/
=> Improve alt text on gallery images

themes/gfsc/layouts/index.html.html
Fixes #307
- Moves screenreader only text higher up the page so that you are looking at the diagram while it is in focus
- Changes order of the text so that description about community groups is read after that and not after the central block.
=> move diagram up the page for better user experience

archetypes/blog/index.md, content/blog/2022/rafft-design-blog/index.md, content/blog/2023/raftt-design-blog-2/index.md, content/blog/2023/raftt-design-diary-3/index.md, themes/gfsc/layouts/partials/relatedblogs.html
preparatory work towards #173
- add the project specific path to a blogs front matter eg https://gfsc.studio/project/the-towers/ -> `project: the-towers`
- add the partial to project layout template `{{- partial "relatedblogs.html" . -}}`
- it will produce a `ul` of related blogs if any exist or nothing.
- not rendering anywhere as of yet because we lack design. I've added it here near the top of a project to screenshot it to prove it's working.
=> add partial that shows blogs related to a project page

content/our-work/category/publications.md
Fixes #351
- Adds new category.tag for publications
- Displays only when content is tagged with this so safe to merge
=> Add publications tag

themes/gfsc/assets/sass/components/_theme-tags.sass, themes/gfsc/assets/sass/pages/_project.sass, themes/gfsc/layouts/partials/themeTags.html, themes/gfsc/layouts/project/single.html
Fixes 352
- Moves tags to the bottom of the project page, directly under content
- Adds descriptive 'see more' text to the start of the tags list
=> Move tags to bottom of project page

themes/gfsc/assets/sass/components/_windows.sass, themes/gfsc/assets/sass/pages/_work.sass
Fixes #335 
- italics removed from the themes "windows" on the homepage
- italics removed from the descriptive paragraph at the top of each  theme/category page.
=> remove italics for legibility

content/contact/index.md
Fixes #380
- redirects visits to `https://gfsc.studio/mailing-list` to `https://gfsc.studio/contact` which displays email addresses and a signup link to the mailing list
=> Alias mailing-list to contact

themes/gfsc/assets/sass/components/_venn.sass, themes/gfsc/layouts/404.html, themes/gfsc/layouts/partials/venn-404.html
Fixes #293 
- Adds a venn diagram to our 404 page with silly reasons given for landing here
- Keeps the main title and adds error 404 to the centre to make sure it's clear still to all users what page this is
- Uses slightly different styling to homepage venn at mobile, to preserve look of diagram as descriptions not required
=> Make 404 page funner

content/team/staff/f/index.md, content/team/staff/rebecca/index.md
Fixes #391
- Set job types to Alum so they do not show up on the team page but retain data so they don't break blogposts, project credits, etc.
=> remove F and Rebecca from the team page

content/team/staff/alfie/index.md, content/team/staff/ivan/index.md, content/team/staff/rosie/index.md
Pretty self explanatory, just cleaning up loose ends.
=> remove developers from staff list as part of redundancy admin
